### ISSUE TITLE
Works FANTASTIC ON LINUX <3

### ISSUE THREAD

**Issue by 4cecoder** [gileli121/GlassCode#17]
WOWIE!!!~~
![image](https://user-images.githubusercontent.com/88108711/200440835-9f96a385-cb01-4f4f-b291-c45b84798413.png)

**Comment by Rdeisenroth** [comment]
How did you archive that?

It should not be working on Linux and currently does not do so for me.

I get the following Error on Arch Linux:
```
java.lang.UnsatisfiedLinkError: Unable to load library 'Advapi32':
libAdvapi32.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
libAdvapi32.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Native library (linux-x86-64/libAdvapi32.so) not found in resource path (/opt/intellij-idea-ultimate-edition/lib/util.jar:/opt/intellij-idea-ultimate-edition/lib/app.jar:/opt/intellij-idea-ultimate-edition/lib/3rd-party-rt.jar:/opt/intellij-idea-ultimate-edition/lib/platform-statistics-devkit.jar:/opt/intellij-idea-ultimate-edition/lib/jps-model.jar:/opt/intellij-idea-ultimate-edition/lib/stats.jar:/opt/intellij-idea-ultimate-edition/lib/protobuf.jar:/opt/intellij-idea-ultimate-edition/lib/external-system-rt.jar:/opt/intellij-idea-ultimate-edition/lib/forms_rt.jar:/opt/intellij-idea-ultimate-edition/lib/intellij-test-discovery.jar:/opt/intellij-idea-ultimate-edition/lib/annotations.jar:/opt/intellij-idea-ultimate-edition/lib/groovy.jar:/opt/intellij-idea-ultimate-edition/lib/3rd-party-native.jar:/opt/intellij-idea-ultimate-edition/lib/annotations-java5.jar:/opt/intellij-idea-ultimate-edition/lib/async-profiler-windows.jar:/opt/intellij-idea-ultimate-edition/lib/async-profiler.jar:/opt/intellij-idea-ultimate-edition/lib/byte-buddy-agent.jar:/opt/intellij-idea-ultimate-edition/lib/error-prone-annotations.jar:/opt/intellij-idea-ultimate-edition/lib/externalProcess-rt.jar:/opt/intellij-idea-ultimate-edition/lib/idea_rt.jar:/opt/intellij-idea-ultimate-edition/lib/intellij-coverage-agent-1.0.682.jar:/opt/intellij-idea-ultimate-edition/lib/jsch-agent.jar:/opt/intellij-idea-ultimate-edition/lib/jsp-base.jar:/opt/intellij-idea-ultimate-edition/lib/junit.jar:/opt/intellij-idea-ultimate-edition/lib/junit4.jar:/opt/intellij-idea-ultimate-edition/lib/platform-objectSerializer-annotations.jar:/opt/intellij-idea-ultimate-edition/lib/rd.jar:/opt/intellij-idea-ultimate-edition/lib/tools-testsBootstrap.jar:/opt/intellij-idea-ultimate-edition/lib/util_rt.jar:/opt/intellij-idea-ultimate-edition/lib/ant/lib/ant.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:307)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:467)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:70)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:737)
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:717)
	at glasscode.helpers.WindowsHelpers.getWindowsBuildNumber(WindowsHelpers.java:57)
	at glasscode.Renderer.<init>(Renderer.java:35)
	at glasscode.PluginMain.getRenderer(PluginMain.java:72)
	at glasscode.PluginMain.enableGlassMode(PluginMain.java:94)
	at glasscode.ui.toolwindow.GlassCodeToolWindow.onEnableCheckBoxChange(GlassCodeToolWindow.java:134)
	at glasscode.ui.toolwindow.GlassCodeToolWindow.lambda$new$4(GlassCodeToolWindow.java:61)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2000)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2320)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:374)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:392)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: java.lang.UnsatisfiedLinkError: libAdvapi32.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:197)
		... 59 more
	Suppressed: java.lang.UnsatisfiedLinkError: libAdvapi32.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:210)
		... 59 more
	Suppressed: java.io.IOException: Native library (linux-x86-64/libAdvapi32.so) not found in resource path (/opt/intellij-idea-ultimate-edition/lib/util.jar:/opt/intellij-idea-ultimate-edition/lib/app.jar:/opt/intellij-idea-ultimate-edition/lib/3rd-party-rt.jar:/opt/intellij-idea-ultimate-edition/lib/platform-statistics-devkit.jar:/opt/intellij-idea-ultimate-edition/lib/jps-model.jar:/opt/intellij-idea-ultimate-edition/lib/stats.jar:/opt/intellij-idea-ultimate-edition/lib/protobuf.jar:/opt/intellij-idea-ultimate-edition/lib/external-system-rt.jar:/opt/intellij-idea-ultimate-edition/lib/forms_rt.jar:/opt/intellij-idea-ultimate-edition/lib/intellij-test-discovery.jar:/opt/intellij-idea-ultimate-edition/lib/annotations.jar:/opt/intellij-idea-ultimate-edition/lib/groovy.jar:/opt/intellij-idea-ultimate-edition/lib/3rd-party-native.jar:/opt/intellij-idea-ultimate-edition/lib/annotations-java5.jar:/opt/intellij-idea-ultimate-edition/lib/async-profiler-windows.jar:/opt/intellij-idea-ultimate-edition/lib/async-profiler.jar:/opt/intellij-idea-ultimate-edition/lib/byte-buddy-agent.jar:/opt/intellij-idea-ultimate-edition/lib/error-prone-annotations.jar:/opt/intellij-idea-ultimate-edition/lib/externalProcess-rt.jar:/opt/intellij-idea-ultimate-edition/lib/idea_rt.jar:/opt/intellij-idea-ultimate-edition/lib/intellij-coverage-agent-1.0.682.jar:/opt/intellij-idea-ultimate-edition/lib/jsch-agent.jar:/opt/intellij-idea-ultimate-edition/lib/jsp-base.jar:/opt/intellij-idea-ultimate-edition/lib/junit.jar:/opt/intellij-idea-ultimate-edition/lib/junit4.jar:/opt/intellij-idea-ultimate-edition/lib/platform-objectSerializer-annotations.jar:/opt/intellij-idea-ultimate-edition/lib/rd.jar:/opt/intellij-idea-ultimate-edition/lib/tools-testsBootstrap.jar:/opt/intellij-idea-ultimate-edition/lib/util_rt.jar:/opt/intellij-idea-ultimate-edition/lib/ant/lib/ant.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:281)
		... 59 more
```
